package com.refcodes.portlets.businesscenter.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the BusinessUser service. Represents a row in the &quot;businesscenter_BusinessUser&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.refcodes.portlets.businesscenter.model.impl.BusinessUserModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.refcodes.portlets.businesscenter.model.impl.BusinessUserImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see BusinessUser
 * @see com.refcodes.portlets.businesscenter.model.impl.BusinessUserImpl
 * @see com.refcodes.portlets.businesscenter.model.impl.BusinessUserModelImpl
 * @generated
 */
public interface BusinessUserModel extends BaseModel<BusinessUser> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a business user model instance should use the {@link BusinessUser} interface instead.
     */

    /**
     * Returns the primary key of this business user.
     *
     * @return the primary key of this business user
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this business user.
     *
     * @param primaryKey the primary key of this business user
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the uuid of this business user.
     *
     * @return the uuid of this business user
     */
    @AutoEscape
    public String getUuid();

    /**
     * Sets the uuid of this business user.
     *
     * @param uuid the uuid of this business user
     */
    public void setUuid(String uuid);

    /**
     * Returns the business user ID of this business user.
     *
     * @return the business user ID of this business user
     */
    public long getBusinessUserId();

    /**
     * Sets the business user ID of this business user.
     *
     * @param businessUserId the business user ID of this business user
     */
    public void setBusinessUserId(long businessUserId);

    /**
     * Returns the business user uuid of this business user.
     *
     * @return the business user uuid of this business user
     * @throws SystemException if a system exception occurred
     */
    public String getBusinessUserUuid() throws SystemException;

    /**
     * Sets the business user uuid of this business user.
     *
     * @param businessUserUuid the business user uuid of this business user
     */
    public void setBusinessUserUuid(String businessUserUuid);

    /**
     * Returns the group ID of this business user.
     *
     * @return the group ID of this business user
     */
    public long getGroupId();

    /**
     * Sets the group ID of this business user.
     *
     * @param groupId the group ID of this business user
     */
    public void setGroupId(long groupId);

    /**
     * Returns the company ID of this business user.
     *
     * @return the company ID of this business user
     */
    public long getCompanyId();

    /**
     * Sets the company ID of this business user.
     *
     * @param companyId the company ID of this business user
     */
    public void setCompanyId(long companyId);

    /**
     * Returns the first name of this business user.
     *
     * @return the first name of this business user
     */
    @AutoEscape
    public String getFirstName();

    /**
     * Sets the first name of this business user.
     *
     * @param firstName the first name of this business user
     */
    public void setFirstName(String firstName);

    /**
     * Returns the last name of this business user.
     *
     * @return the last name of this business user
     */
    @AutoEscape
    public String getLastName();

    /**
     * Sets the last name of this business user.
     *
     * @param lastName the last name of this business user
     */
    public void setLastName(String lastName);

    /**
     * Returns the email of this business user.
     *
     * @return the email of this business user
     */
    @AutoEscape
    public String getEmail();

    /**
     * Sets the email of this business user.
     *
     * @param email the email of this business user
     */
    public void setEmail(String email);

    /**
     * Returns the owner ship of this business user.
     *
     * @return the owner ship of this business user
     */
    @AutoEscape
    public String getOwnerShip();

    /**
     * Sets the owner ship of this business user.
     *
     * @param ownerShip the owner ship of this business user
     */
    public void setOwnerShip(String ownerShip);

    /**
     * Returns the category ID of this business user.
     *
     * @return the category ID of this business user
     */
    public long getCategoryId();

    /**
     * Sets the category ID of this business user.
     *
     * @param categoryId the category ID of this business user
     */
    public void setCategoryId(long categoryId);

    /**
     * Returns the phone number of this business user.
     *
     * @return the phone number of this business user
     */
    @AutoEscape
    public String getPhoneNumber();

    /**
     * Sets the phone number of this business user.
     *
     * @param phoneNumber the phone number of this business user
     */
    public void setPhoneNumber(String phoneNumber);

    /**
     * Returns the created date of this business user.
     *
     * @return the created date of this business user
     */
    public Date getCreatedDate();

    /**
     * Sets the created date of this business user.
     *
     * @param createdDate the created date of this business user
     */
    public void setCreatedDate(Date createdDate);

    /**
     * Returns the created by of this business user.
     *
     * @return the created by of this business user
     */
    public long getCreatedBy();

    /**
     * Sets the created by of this business user.
     *
     * @param createdBy the created by of this business user
     */
    public void setCreatedBy(long createdBy);

    /**
     * Returns the updated date of this business user.
     *
     * @return the updated date of this business user
     */
    public Date getUpdatedDate();

    /**
     * Sets the updated date of this business user.
     *
     * @param updatedDate the updated date of this business user
     */
    public void setUpdatedDate(Date updatedDate);

    /**
     * Returns the updated by of this business user.
     *
     * @return the updated by of this business user
     */
    public long getUpdatedBy();

    /**
     * Sets the updated by of this business user.
     *
     * @param updatedBy the updated by of this business user
     */
    public void setUpdatedBy(long updatedBy);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(BusinessUser businessUser);

    @Override
    public int hashCode();

    @Override
    public CacheModel<BusinessUser> toCacheModel();

    @Override
    public BusinessUser toEscapedModel();

    @Override
    public BusinessUser toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
