package com.refcodes.portlets.businesscenter.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.refcodes.portlets.businesscenter.model.BusinessUser;
import com.refcodes.portlets.businesscenter.service.BusinessUserLocalServiceUtil;

/**
 * The extended model base implementation for the BusinessUser service. Represents a row in the &quot;businesscenter_BusinessUser&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BusinessUserImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see BusinessUserImpl
 * @see com.refcodes.portlets.businesscenter.model.BusinessUser
 * @generated
 */
public abstract class BusinessUserBaseImpl extends BusinessUserModelImpl
    implements BusinessUser {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a business user model instance should use the {@link BusinessUser} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            BusinessUserLocalServiceUtil.addBusinessUser(this);
        } else {
            BusinessUserLocalServiceUtil.updateBusinessUser(this);
        }
    }
}
